// Generated by scripts/generate-book-tier-manifest.mjs. Do not edit manually.
export const BOOKS_2026_FILES = [
  'a_01.jpg',
  'a_02.jpg',
  'a_03.jpg',
  'b_01.jpg',
  'b_03.jpg',
  'b_05.jpg',
  'c_01.jpg',
  'c_02.jpg',
  'd_01.jpg',
  's_01.jpg',
  's_02.jpg',
  's_03.jpg',
] as const;
