import { PortfolioContentSnapshot, ProjectStory } from '../models/portfolio-content.model';

const project = (value: ProjectStory): ProjectStory => value;

export const PORTFOLIO_CONTENT_DATA: PortfolioContentSnapshot = {
  technologies: [
    { id: 'angular', label: 'Angular', icon: 'angular_logo.svg', group: 'frontend' },
    { id: 'rxjs', label: 'RxJS', icon: 'rxjs_logo.svg', group: 'frontend' },
    { id: 'nx', label: 'NX', icon: 'nx_logo.svg', group: 'frontend' },
    { id: 'flutter', label: 'Flutter', icon: 'flutter_logo.svg', group: 'frontend' },
    { id: 'riverpod', label: 'Riverpod', icon: 'riverpod_logo.svg', group: 'frontend' },
    { id: 'typescript', label: 'TypeScript', icon: 'typescript_logo.svg', group: 'language' },
    { id: 'web', label: 'HTML, CSS & JavaScript', icon: 'web_logo.svg', group: 'language' },
    { id: 'dart', label: 'Dart', icon: 'dart_logo.svg', group: 'language' },
    { id: 'bootstrap', label: 'Bootstrap', icon: 'bootstrap_logo.svg', group: 'ui' },
    { id: 'material', label: 'Material Design', icon: 'material_logo.svg', group: 'ui' },
    { id: 'tailwind', label: 'Tailwind', icon: 'tailwind_logo.svg', group: 'ui' },
    { id: 'firebase', label: 'Firebase', icon: 'firebase_logo.svg', group: 'backend' },
    { id: 'pocketbase', label: 'PocketBase', icon: 'pocketbase_logo.svg', group: 'backend' },
    { id: 'mongodb', label: 'MongoDB', icon: 'mongodb_logo.svg', group: 'backend' },
    { id: 'node', label: 'Node.js', icon: 'nodejs_logo.svg', group: 'backend' },
    { id: 'graphql', label: 'GraphQL', icon: 'graphql_logo.svg', group: 'backend' },
    { id: 'swagger', label: 'Swagger', icon: 'swagger_logo.svg', group: 'tooling' },
    { id: 'jenkins', label: 'Jenkins', icon: 'jenkins_logo.svg', group: 'delivery' },
    { id: 'github', label: 'GitHub', icon: 'github_logo_black.svg', group: 'delivery' },
    { id: 'bitbucket', label: 'Bitbucket', icon: 'bitbucket_logo.svg', group: 'delivery' },
    { id: 'clickup', label: 'ClickUp', icon: 'clickup_logo.svg', group: 'tooling' },
    { id: 'jira', label: 'Jira', icon: 'jira_logo.svg', group: 'tooling' },
    { id: 'trello', label: 'Trello', icon: 'trello_logo.svg', group: 'tooling' },
    { id: 'figma', label: 'Figma', icon: 'figma_logo.svg', group: 'tooling' },
    { id: 'jasmine', label: 'Jasmine', icon: 'jasmine_logo.svg', group: 'tooling' },
    { id: 'karma', label: 'Karma', icon: 'karma_logo.svg', group: 'tooling' },
  ],
  projects: [
    project({
      legacyId: '1',
      slug: 'monto',
      name: 'Monto',
      description: 'A mobile and web rental platform built with Flutter.',
      thumbnail: {
        src: 'assets/images/monto/monto_phones.webp',
        alt: 'Monto mobile application screens',
        width: 1600,
        height: 688,
      },
      logo: { src: 'assets/images/monto/monto_logo.jpg', alt: 'Monto logo', width: 240, height: 240 },
      technologies: ['flutter', 'dart', 'riverpod', 'mongodb', 'graphql', 'material', 'clickup'],
      projectType: 'WORK',
      year: 2022,
      featuredOrder: 1,
      liveUrl: 'https://monto-rent.com',
      contribution:
        'I implemented large and small parts of the Flutter frontend and later led work on its web version.',
      outcome: 'The project established my direction in cross-platform application development.',
      blocks: [
        {
          kind: 'paragraph',
          text: 'As part of my computer science AP degree, I collaborated with the app agency LittleGiants to develop Monto for one of their clients.',
        },
        {
          kind: 'paragraph',
          text: 'Monto is a Danish rental platform where private individuals and businesses can rent out everyday items in their local area.',
        },
        { kind: 'heading', level: 2, text: 'Notable features' },
        {
          kind: 'list',
          style: 'unordered',
          items: [
            'Rental item CRUD and image upload',
            'Rental calendar periods and bulk discounts',
            'Keyword, category, and geographic filtering',
            'Rental agreement management',
            'One-to-one live chat',
            'Reviews and ratings',
            'Administrative category, report, and statistics tools',
          ],
        },
        {
          kind: 'media',
          media: {
            src: 'assets/gifs/monto.gif',
            alt: 'Monto application interaction preview',
            width: 1718,
            height: 1266,
          },
        },
        {
          kind: 'paragraph',
          text: 'My role was to implement the Flutter frontend. It was my first cross-platform project and gave me responsibility across both large and small product areas.',
        },
        {
          kind: 'paragraph',
          text: 'The work developed my understanding of component architecture, mobile interface practice, and real project delivery. About a year later I returned to implement the web version and served as lead developer for a period.',
        },
      ],
    }),
    project({
      legacyId: '2',
      slug: 'up-n-down',
      name: "Up N' Down",
      description: 'A Flutter golf exercise and training application.',
      thumbnail: {
        src: 'assets/images/und/und_phones.webp',
        alt: "Up N' Down application screens",
        width: 1084,
        height: 1600,
      },
      logo: { src: 'assets/images/und/und_logo.jpg', alt: "Up N' Down logo", width: 240, height: 240 },
      technologies: ['flutter', 'dart', 'riverpod', 'mongodb', 'graphql', 'material', 'clickup'],
      projectType: 'WORK',
      year: 2022,
      featuredOrder: 4,
      liveUrl: 'https://upndown.dk',
      contribution: 'I implemented the supplied design against an existing GraphQL backend.',
      outcome: 'The frontend reached roughly 95% completion during the first month.',
      blocks: [
        {
          kind: 'paragraph',
          text: "Up N' Down was one of my first projects as a newly hired frontend developer. The client wanted a platform that helped golfers improve and discover new exercises.",
        },
        {
          kind: 'paragraph',
          text: 'The application uses golf-related input to recommend exercises and tips. Visitors can also browse more than 50 video exercises with step-by-step guidance.',
        },
        { kind: 'heading', level: 2, text: 'Notable features' },
        {
          kind: 'list',
          style: 'unordered',
          items: [
            'Onboarding with golf-related input',
            'A custom exercise video player',
            'Likes, saved exercises, and challenges',
            'Administrative category, reporting, and exercise-upload tools',
          ],
        },
        {
          kind: 'callout',
          title: 'My contribution',
          text: 'The client supplied the design and a developed GraphQL backend. I implemented the frontend in a linear delivery process that reached roughly 95% completion in the first month.',
        },
      ],
    }),
    project({
      legacyId: '3',
      slug: 'myepi',
      name: 'MyEpi',
      description: 'Seizure tracking and Apple Watch detection support.',
      thumbnail: {
        src: 'assets/images/myepi/epi_home.jpg',
        alt: 'MyEpi mobile application home screen',
        width: 997,
        height: 581,
      },
      logo: { src: 'assets/images/myepi/epi_logo.jpg', alt: 'MyEpi logo', width: 240, height: 240 },
      technologies: ['flutter', 'dart', 'riverpod', 'firebase', 'figma', 'clickup'],
      projectType: 'WORK',
      year: 2023,
      featuredOrder: 2,
      liveUrl: 'https://www.myepi.dk/',
      contribution: 'I refined the interface, implemented periodic PDF generation, and restructured state management.',
      blocks: [
        {
          kind: 'paragraph',
          text: 'MyEpi is intended to make life safer for people living with epilepsy. I joined after its MVP phase to help move the existing application forward.',
        },
        { kind: 'heading', level: 2, text: 'Mobile application' },
        {
          kind: 'paragraph',
          text: 'Patients can record seizures and follow community updates, while family members can receive the time and location of a seizure registered by an Apple Watch.',
        },
        { kind: 'heading', level: 2, text: 'Watch application' },
        {
          kind: 'paragraph',
          text: 'The watch application uses built-in sensor technology to detect seizure-characteristic movement and send alerts to family members.',
        },
        {
          kind: 'list',
          style: 'unordered',
          items: [
            'Apple Watch seizure detection',
            'Family notifications through notification or SMS',
            'Automatic and manual seizure history',
            'Periodic PDF documentation',
          ],
        },
        {
          kind: 'media',
          media: {
            src: 'assets/images/myepi/epi_screens.webp',
            alt: 'MyEpi application screen collection',
            width: 1600,
            height: 674,
          },
        },
        {
          kind: 'paragraph',
          text: 'I fine-tuned much of the interface to a new design and implemented periodic PDF generation. I also removed redundant code and restructured state management with Riverpod.',
        },
      ],
    }),
    project({
      legacyId: '4',
      slug: 'selvhent',
      name: 'Selvhent',
      description: 'A digital parcel-shop management system.',
      thumbnail: {
        src: 'assets/images/selvhent/selvhent_customer.jpg',
        alt: 'Selvhent customer kiosk',
        width: 678,
        height: 417,
      },
      logo: { src: 'assets/images/selvhent/selvhent_logo.jpg', alt: 'Selvhent logo', width: 240, height: 240 },
      technologies: ['flutter', 'dart', 'riverpod', 'mongodb', 'graphql', 'clickup'],
      projectType: 'WORK',
      year: 2022,
      featuredOrder: 3,
      liveUrl: 'https://selvhent.com/',
      contribution:
        'I implemented the web administration application and pickup-request handling in the warehouse unit.',
      blocks: [
        {
          kind: 'paragraph',
          text: 'Selvhent is a digital warehouse-management system for parcel shops, designed to simplify storage, retrieval, and the handling of unclaimed packages.',
        },
        {
          kind: 'paragraph',
          text: 'The product combines a customer kiosk for package information with a tablet-based warehouse unit that tracks package locations.',
        },
        { kind: 'heading', level: 2, text: 'Notable features' },
        {
          kind: 'list',
          style: 'unordered',
          items: [
            'Package inventory visibility for employees',
            'Customer input for couriers, package numbers, and bulk pickups',
            'Administration of shops, couriers, and their connections',
          ],
        },
        {
          kind: 'media',
          media: {
            src: 'assets/images/selvhent/selvhent_employee.jpg',
            alt: 'Selvhent warehouse application in use',
            width: 1200,
            height: 800,
          },
        },
        {
          kind: 'paragraph',
          text: 'My role was to implement the Flutter web administration application and handle pickup requests in the warehouse unit.',
        },
      ],
    }),
    project({
      legacyId: '5',
      slug: 'mealbuilder',
      name: 'Mealbuilder',
      description: 'Recipe planning with detailed nutrition information.',
      thumbnail: {
        src: 'assets/images/mealbuilder/mealbuilder_screens.webp',
        alt: 'Mealbuilder application screens',
        width: 1600,
        height: 674,
      },
      logo: { src: 'assets/images/mealbuilder/mealbuilder_logo.jpg', alt: 'Mealbuilder logo', width: 240, height: 240 },
      technologies: ['flutter', 'dart', 'riverpod', 'swagger', 'material', 'clickup'],
      projectType: 'WORK',
      year: 2023,
      featuredOrder: 5,
      blocks: [
        {
          kind: 'paragraph',
          text: 'Mealbuilder helps users control calorie intake and nutrient distribution while providing recipes for quick meals.',
        },
        {
          kind: 'paragraph',
          text: 'Recipes can be customized to match personal preferences, calorie targets, and macronutrient goals.',
        },
        {
          kind: 'media',
          media: {
            src: 'assets/images/mealbuilder/mealbuilder_two.jpg',
            alt: 'Mealbuilder recipe and nutrition screens',
            width: 1239,
            height: 695,
          },
        },
      ],
    }),
  ],
  profile: {
    name: 'Marc Klesiewicz',
    role: 'Frontend and app developer',
    location: 'Near Odense, Denmark',
    introduction: [
      "I'm an app developer with a computer science background, originally from Lolland and now settled near Odense with my girlfriend Mathilde and our dog Cody.",
      'I focus on frontend and cross-platform applications. Away from software I gravitate toward music, film, board games, padel, mechanical keyboards, and the ongoing renovation of an old house.',
      'I value genuine communities and meaningful goals. My best work combines reliable engineering with an interface that feels considered and intuitive.',
    ],
    portrait: { src: 'assets/images/me.webp', alt: 'Portrait of Marc Klesiewicz', width: 1058, height: 1600 },
    avatar: { src: 'assets/images/avatar.webp', alt: '', width: 870, height: 851 },
    endorsement: {
      quote:
        'Marc is an extremely competent employee who works independently, finds constructive solutions, and takes significant responsibility. He is also a cheerful and helpful colleague.',
      attribution: 'Steffen Engsig Aagaard, CEO at LittleGiants',
    },
    capabilityGroups: [
      { title: 'Interfaces', technologyIds: ['angular', 'typescript', 'rxjs', 'flutter', 'dart', 'riverpod'] },
      { title: 'Product delivery', technologyIds: ['figma', 'graphql', 'firebase', 'mongodb', 'github', 'jenkins'] },
    ],
    experience: [
      {
        organization: 'Autorola',
        role: 'Frontend web developer',
        start: '2023',
        end: 'Current',
        description: [
          'Developing and maintaining responsive frontend applications for the Autorola Marketplace platform.',
          'Daily work with Angular, TypeScript, RxJS, and Bootstrap.',
          'Participating in code reviews, iteration planning, and refinement.',
        ],
        logo: { src: 'assets/images/autorola_logo.jpg', alt: 'Autorola logo', width: 200, height: 200 },
      },
      {
        organization: 'Little Giants',
        role: 'App developer',
        start: '2022',
        end: '2023',
        description: [
          'Helping startup companies develop mobile and web applications.',
          'Building cross-platform frontends with Flutter, Dart, Riverpod, and GraphQL.',
        ],
        logo: { src: 'assets/images/littlegiants_logo.png', alt: 'Little Giants logo', width: 300, height: 300 },
      },
      {
        organization: 'Restaurant Eventyr Golf',
        role: 'Waiter',
        start: '2021',
        end: '2022',
        description: ['Serving food and beverages to guests.'],
        logo: { src: 'assets/images/eventyrgolf_logo.png', alt: 'Eventyr Golf logo', width: 234, height: 220 },
      },
      {
        organization: 'Danski',
        role: 'Vacation coordinator',
        start: '2018',
        end: '2019',
        description: [
          'Guiding ski tours and helping guests with ski activities.',
          'Leading mountain groups with attention to safety and enjoyment.',
        ],
        logo: { src: 'assets/images/danski_logo.png', alt: 'Danski logo', width: 500, height: 500 },
      },
      {
        organization: 'Guldborgsundhallerne',
        role: 'Lifeguard and instructor',
        start: '2012',
        end: '2020',
        description: ['Keeping swimmers and visitors safe.', 'Planning and facilitating exercise classes.'],
        logo: { src: 'assets/images/scf_logo.jpg', alt: 'Guldborgsundhallerne logo', width: 225, height: 225 },
      },
    ],
    contacts: [],
  },
};
